# Generated by Django 4.1.1 on 2023-04-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Категория больного')),
            ],
            options={
                'verbose_name': 'Категория больного',
                'verbose_name_plural': 'Категории больных',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CircumstancesOfDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Обстоятельства выявления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Обстоятельства выявления',
                'verbose_name_plural': 'Обстоятельства выявления',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'Житель',
                'verbose_name_plural': 'Жители',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=600, verbose_name='Диагноз')),
                ('mkb', models.CharField(db_index=True, max_length=50, verbose_name='МКБ-10')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
                'ordering': ['title', 'mkb'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='GroupOfDiagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Группа диагнозов')),
            ],
            options={
                'verbose_name': 'Группа диагнозов',
                'verbose_name_plural': 'Группы диагнозов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Лабораторное подтверждение')),
            ],
            options={
                'verbose_name': 'Лабораторное подтверждение',
                'verbose_name_plural': 'Лабораторные подтверждения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaceOfDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Основное место Обращения')),
            ],
            options={
                'verbose_name': 'Основное место Обращения',
                'verbose_name_plural': 'Основные места Обращения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Места работы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=7, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Социальная группа')),
            ],
            options={
                'verbose_name': 'Социальная группа',
                'verbose_name_plural': 'Социальные группы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Врач')),
                ('place_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.placeofwork', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MestoObracheniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Место Обращения')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть данные')),
                ('osnovnoe_mesto_obr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.placeofdetection', verbose_name='Основное место')),
            ],
            options={
                'verbose_name': 'Место Обращения',
                'verbose_name_plural': 'Места Обращения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IndexForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_bith', models.DateField(max_length=10, verbose_name='Дата рождения')),
                ('locality', models.CharField(help_text='г. Саратов', max_length=100, verbose_name='Населенный пункт')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.CharField(max_length=20, verbose_name='Дом')),
                ('body', models.CharField(blank=True, max_length=20, verbose_name='Корпус')),
                ('flat', models.CharField(blank=True, max_length=20, verbose_name='Квартира')),
                ('job', models.CharField(blank=True, max_length=150, verbose_name='Место работы')),
                ('date_of_application', models.DateField(max_length=10, verbose_name='Дата обращения')),
                ('date_of_establishment', models.DateField(max_length=10, verbose_name='Дата установления')),
                ('DATE_ZAP', models.DateField(max_length=10, verbose_name='DATE_ZAP')),
                ('VRACH', models.CharField(max_length=50, verbose_name='VRACH')),
                ('create_at1', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.category1', verbose_name='Категория больного')),
                ('circumstances_of_detection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.circumstancesofdetection', verbose_name='Обстоятельства выявления')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.citizen', verbose_name='Житель')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.diagnosis', verbose_name='Диагноз')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.district', verbose_name='Район')),
                ('group_of_diagnoses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.groupofdiagnoses', verbose_name='Группа диагнозов')),
                ('laboratory_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.laboratoryconfirmation', verbose_name='Лабораторное подтверждение')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.physician', verbose_name='Врач')),
                ('place_of_detection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.mestoobracheniya', verbose_name='Место выявления')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.post', verbose_name='Должность')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.sex', verbose_name='Пол')),
                ('social_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.socialgroup', verbose_name='Социальная группа')),
            ],
            options={
                'verbose_name': 'Извещение',
                'verbose_name_plural': 'Извещения',
                'ordering': ['lastname', 'date_bith'],
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='group_of_diagnoses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.groupofdiagnoses', verbose_name='Группа диагнозов'),
        ),
    ]
