# Generated by Django 4.1.1 on 2023-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть данные'),
        ),
    ]
