# Generated by Django 4.1.1 on 2023-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_physician_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofdetection',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть данные'),
        ),
    ]
