# Generated by Django 4.1.1 on 2023-04-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_placeofdetection_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexform',
            name='group_of_diagnoses',
        ),
    ]
