# Generated by Django 4.1.1 on 2023-05-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_indexform_group_of_diagnoses'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexform',
            name='DATA_ZAP',
            field=models.DateTimeField(max_length=10, null=True, verbose_name='DATA_ZAP'),
        ),
    ]
