# Generated by Django 4.1.1 on 2023-05-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_indexform_data_zap'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexform',
            name='mesto_obracheniya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.mestoobracheniya', verbose_name='Место выявления'),
        ),
        migrations.AlterField(
            model_name='indexform',
            name='place_of_detection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.placeofdetection', verbose_name='Основное место'),
        ),
    ]
