# Generated by Django 4.1.1 on 2023-05-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_indexform_mesto_obracheniya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexform',
            name='DATA_ZAP',
        ),
        migrations.AlterField(
            model_name='indexform',
            name='create_at1',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
