# Generated by Django 4.1.1 on 2023-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_indexform_data_zap_alter_indexform_create_at1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='placeofdetection',
            options={'ordering': ['title'], 'verbose_name': 'Основное место обращения', 'verbose_name_plural': 'Основные места обращения'},
        ),
        migrations.AlterField(
            model_name='circumstancesofdetection',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Скрыто'),
        ),
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(max_length=10, null=True, verbose_name='DATE_ZAP'),
        ),
        migrations.AlterField(
            model_name='placeofdetection',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Основное место обращения'),
        ),
    ]
