# Generated by Django 4.1.1 on 2023-05-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexform',
            name='group_of_diagnoses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.groupofdiagnoses', verbose_name='Группа диагнозов'),
        ),
    ]
