# Generated by Django 4.1.1 on 2023-05-17 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_indexform_group_of_diagnoses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=datetime.date(2023, 5, 1), max_length=10, null=True, verbose_name='DATE_ZAP'),
        ),
        migrations.AlterField(
            model_name='indexform',
            name='create_at1',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
