# Generated by Django 4.1.1 on 2023-05-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_indexform_date_zap_alter_indexform_create_at1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 10, 13, 3, 53057, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='DATE_ZAP'),
        ),
    ]
