# Generated by Django 4.1.1 on 2023-05-17 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_indexform_date_zap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 10, 28, 39, 974944, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='DATE_ZAP'),
        ),
    ]
