# Generated by Django 4.1.1 on 2023-05-17 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_indexform_date_zap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=datetime.date(2023, 5, 1), max_length=10, null=True, verbose_name='DATE_ZAP'),
        ),
    ]
