# Generated by Django 4.1.1 on 2023-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_indexform_date_zap'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexform',
            name='LAB_POT_RAS',
            field=models.CharField(max_length=50, null=True, verbose_name='LAB_POT_RAS'),
        ),
    ]
