# Generated by Django 4.1.1 on 2023-05-18 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_indexform_lab_pot_ras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=datetime.date(2023, 5, 1), verbose_name='DATE_ZAP'),
        ),
    ]
