# Generated by Django 4.1.1 on 2023-06-20 08:44

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_indexform_date_zap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexform',
            name='DATE_ZAP',
            field=models.DateField(default=home.models.get_first_day_of_month),
        ),
        migrations.AlterField(
            model_name='indexform',
            name='body',
            field=models.CharField(blank=True, max_length=100, verbose_name='Корпус'),
        ),
    ]
