# Generated by Django 4.1.1 on 2023-06-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_indexform_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexform',
            name='group_of_diagnoses',
        ),
    ]
