# Generated by Django 4.1.1 on 2023-08-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_indexform_group_of_diagnoses'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(db_index=True, max_length=1200, verbose_name='О нас')),
                ('work_mode', models.TextField(db_index=True, max_length=1200, verbose_name='Режим работы')),
                ('activity', models.TextField(db_index=True, max_length=1200, verbose_name='Деятельность')),
                ('address1', models.TextField(db_index=True, max_length=100, verbose_name='Адрес 1')),
                ('number1', models.CharField(db_index=True, max_length=20, verbose_name='Номер 1')),
                ('address2', models.CharField(db_index=True, max_length=100, verbose_name='Адрес 2')),
                ('number2', models.CharField(db_index=True, max_length=20, verbose_name='Номер 2')),
                ('address3', models.CharField(db_index=True, max_length=100, verbose_name='Адрес 3')),
                ('number3', models.CharField(db_index=True, max_length=20, verbose_name='Номер 3')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
                'ordering': ['about', 'work_mode', 'activity'],
            },
        ),
    ]
