# Generated by Django 4.1.1 on 2023-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_infomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрытие месяца')),
            ],
            options={
                'verbose_name': 'Закрытие месяца',
                'verbose_name_plural': 'Закрытие месяца',
            },
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['id', 'title', 'mkb'], 'verbose_name': 'Диагноз', 'verbose_name_plural': 'Диагнозы'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='indexform',
            options={'ordering': ['-id', 'lastname', 'date_bith'], 'verbose_name': 'Извещение', 'verbose_name_plural': 'Извещения'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'ordering': ['id'], 'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
    ]
