# Generated by Django 4.1.1 on 2023-08-17 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_monthclosure_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
